jobs:
  clear:
    name: Delete all caches
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clear caches
      uses: easimon/wipe-cache@v2
name: Clear cache
on:
  repository_dispatch:
    types: trigger-ga___cache.yml
