env:
  CI: true
jobs:
  frogbot:
    if: endsWith(${{ needs.precheck.outputs.version }}, '-SNAPSHOT')
    name: Frogbot
    needs:
    - precheck
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      name: Decrypt secrets
      run: sh .github/scripts/decrypt-secrets.sh
      shell: bash
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: ${{ vars.JAVA_DISTRO }}
        java-version: ${{ vars.JAVA_VERSION }}
    - continue-on-error: true
      env:
        JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
        JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JF_URL: ${{ secrets.JFROG_PLATFORM_URL }}
        JRELEASER_OCI_COMPARTMENTID: ${{ secrets.JRELEASER_OCI_COMPARTMENTID }}
      uses: jfrog/frogbot@5d0e9daa940c15717f1258ada5d841dace6ed538
  precheck:
    name: Precheck
    secrets: inherit
    uses: jreleaser/jreleaser/.github/workflows/step-precheck.yml@main
name: Frogbot
on:
  repository_dispatch:
    types: trigger-ga___frogbot.yml
permissions:
  actions: write
  contents: write
  pull-requests: write
  security-events: write
