jobs:
  native-image:
    name: ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - continue-on-error: true
      name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: plugins
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: ${{ vars.JAVA_DISTRO }}
        java-version: ${{ vars.JAVA_VERSION }}
    - continue-on-error: true
      if: endsWith(${{ inputs.project-version }}, '-SNAPSHOT') != true
      name: Version
      run: 'echo ${{ inputs.project-version }} > VERSION

        '
    - continue-on-error: true
      name: Jdks
      run: ./gradlew :jreleaser:copyJdksFromCache :jreleaser:setupJdks
      shell: bash
    - continue-on-error: true
      env:
        JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}
      name: NativeImage
      uses: jreleaser/release-action@v2
      with:
        arguments: assemble --assembler native-image --select-current-platform
        setup-java: false
        version: early-access
    - continue-on-error: true
      if: always()
      name: JReleaser output
      uses: actions/upload-artifact@v4
      with:
        name: jreleaser-native-image-${{ runner.os }}-${{ runner.arch }}
        path: 'out/jreleaser/trace.log

          out/jreleaser/output.properties

          '
    - continue-on-error: true
      name: Stop Gradle daemon
      run: ./gradlew -stop
      shell: bash
    - continue-on-error: true
      name: Upload native-image
      uses: actions/upload-artifact@v4
      with:
        name: native-image-${{ runner.os }}-${{ runner.arch }}
        path: 'out/jreleaser/assemble/jreleaser-native/native-image/*.zip

          '
        retention-days: 1
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        - macos-14
name: X-NativeImage
on:
  repository_dispatch:
    types: trigger-ga___step-native-image.yml
permissions:
  contents: read
