jobs:
  jlink:
    env:
      CI: true
    name: Jlink
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}
      name: Decrypt secrets
      run: sh .github/scripts/decrypt-secrets.sh
      shell: bash
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: ${{ vars.JAVA_DISTRO }}
        java-version: ${{ vars.JAVA_VERSION }}
    - continue-on-error: true
      if: endsWith(${{ inputs.project-version }}, '-SNAPSHOT') != true
      name: Version
      run: 'echo ${{ inputs.project-version }} > VERSION

        '
    - continue-on-error: true
      env:
        JRELEASER_OCI_COMPARTMENTID: ${{ secrets.oci-compartment-id }}
      name: Build
      run: ./gradlew -Prelease=true -PreproducibleBuild=true build -S
    - continue-on-error: true
      env:
        JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}
      name: Java Archive
      uses: jreleaser/release-action@v2
      with:
        arguments: assemble --assembler java-archive
        setup-java: false
        version: early-access
    - continue-on-error: true
      env:
        JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}
      name: Jlink
      uses: jreleaser/release-action@v2
      with:
        arguments: assemble --assembler jlink
        setup-java: false
        version: early-access
    - continue-on-error: true
      if: always()
      name: JReleaser output
      uses: actions/upload-artifact@v4
      with:
        name: jreleaser-jlink
        path: 'out/jreleaser/trace.log

          out/jreleaser/output.properties

          '
    - continue-on-error: true
      name: Dependencies
      run: 'ls -l plugins/jreleaser/build/dependencies/flat

        ls -l plugins/jreleaser/build/dependencies/graalvm

        '
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: 'plugins/jreleaser/build/libs/

          plugins/jreleaser/build/dependencies/

          plugins/jreleaser/build/distributions/

          plugins/jreleaser-tool-provider/build/libs/*.jar

          plugins/jreleaser-ant-tasks/build/distributions/*.zip

          '
        retention-days: 1
    - continue-on-error: true
      name: Stop Gradle daemon
      run: ./gradlew -stop
      shell: bash
    - continue-on-error: true
      name: Upload java-archive
      uses: actions/upload-artifact@v4
      with:
        name: java-archive
        path: 'out/jreleaser/assemble/jreleaser/java-archive/*.zip

          out/jreleaser/assemble/jreleaser/java-archive/*.tar

          '
        retention-days: 1
    - continue-on-error: true
      name: Upload jlink
      uses: actions/upload-artifact@v4
      with:
        name: jlink
        path: 'out/jreleaser/assemble/jreleaser-standalone/jlink/*.zip

          '
        retention-days: 1
name: X-Jlink
on:
  repository_dispatch:
    types: trigger-ga___step-jlink.yml
permissions:
  contents: read
