jobs:
  update-wiki:
    name: Update wiki for Release ${{ inputs.project-tag }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Checkout wiki
      uses: actions/checkout@v4
      with:
        path: wiki
        repository: jreleaser/jreleaser.wiki
        token: ${{ secrets.gh-access-token }}
    - continue-on-error: true
      name: Download checksums
      run: 'curl -sL https://github.com/jreleaser/jreleaser/releases/download/${{
        inputs.project-tag }}/checksums_sha256.txt --output checksums_sha256.txt

        '
      shell: bash
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.gh-access-token }}
        JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}
      name: Generate wiki page
      uses: jreleaser/release-action@v2
      with:
        arguments: template eval --changelog --input-file src/jreleaser/templates/wiki-release-page.md.tpl
          --target-directory wiki/Releases ${{ inputs.template-params }}
        version: early-access
    - continue-on-error: true
      env:
        GH_BOT_EMAIL: ${{ vars.GH_BOT_EMAIL }}
        TAG: ${{ inputs.project-tag }}
        VERSION: ${{ inputs.project-version }}
      name: Commit
      run: sh .github/scripts/update-wiki.sh
      shell: bash
name: X-UpdateWiki
on:
  repository_dispatch:
    types: trigger-ga___step-update-wiki.yml
permissions:
  actions: read
  contents: write
  id-token: write
