jobs:
  earlyaccess:
    name: Trigger Early Access
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: ${{ vars.JAVA_DISTRO }}
        java-version: ${{ vars.JAVA_VERSION }}
    - continue-on-error: true
      name: Build
      run: ./gradlew -PreproducibleBuild=true build -S
    - continue-on-error: true
      name: Rename artifacts
      run: 'mkdir early-access

        cp plugins/jreleaser-tool-provider/build/VERSION early-access/VERSION

        cp plugins/jreleaser-tool-provider/build/libs/jreleaser-tool-provider-*-SNAPSHOT.jar
        early-access/jreleaser-tool-provider-early-access.jar

        cp plugins/jreleaser/build/distributions/jreleaser-*-SNAPSHOT.zip early-access/jreleaser-early-access.zip

        cp plugins/jreleaser-ant-tasks/build/distributions/jreleaser-ant-tasks-*-SNAPSHOT.zip
        early-access/jreleaser-ant-tasks-early-access.zip

        '
    - continue-on-error: true
      name: Release early-access artifacts
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: early-access
        files: 'early-access/*

          '
        prerelease: true
        repo_token: ${{ secrets.GIT_ACCESS_TOKEN }}
        title: JReleaser Early-Access
name: Trigger Early Access
on:
  repository_dispatch:
    types: trigger-ga___trigger-early-access.yml
permissions:
  contents: read
